### ISSUE TITLE
Excess dep

### ISSUE THREAD

**Issue by r4v3n6101** [JustAGod1/sc-api-rs#1]
https://github.com/JustAGod1/sc-api-rs/blob/7ad97b68c036606f95c84408e1a25c1f72f4b159/src/client.rs#L65
`Tokio` already contains async mutexes
Furthermore, short critical section will be handled faster w/ standard Mutexes, because of opt-outing async glue.

**Comment by JustAGod1** [comment]
Thanks for pointing out excess dep. Will remove it asap.  
About async mutex. I probably can't agree with you that it's short critical section. It contains http request, and it may take long time to complete. Therefore, using non-async mutex here may nullify pros of async http requests.

**Comment by r4v3n6101** [comment]
That makes sense!
